sudo: false

language: php

php:
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_script:
  - composer selfupdate
  - composer install

test:
  script:
    - composer test
